### ISSUE TITLE
0 Projects found when on a Networked Drive

### ISSUE THREAD

**Issue by 15four** [teammixture/recents-settings#18]
Recents finds projects perfectly when the root folder is local, but finds nothing when the root folder is on a networked drive.

![screen shot 2013-12-12 at 11 47 36 am](https://f.cloud.github.com/assets/3717679/1734895/2b7bd674-634d-11e3-807e-18209f345f83.png)
![screen shot 2013-12-12 at 11 47 52 am](https://f.cloud.github.com/assets/3717679/1734896/2d8a17dc-634d-11e3-9e5b-51690ce30e69.png)

**Comment by petetak** [comment]
Hi,
These are the constants that I can possibly include - which of them would cover your drive do you think:

NSMetadataQueryUserHomeScope
Search the user’s home directory.

NSMetadataQueryLocalComputerScope
Search all local mounted volumes, including the user home directory. The user’s home directory is searched even if it is a remote volume.

NSMetadataQueryNetworkScope
Search all user-mounted remote volumes.

NSMetadataQueryUbiquitousDocumentsScope
Search all files in the Documents directories of the application’s iCloud container directories.

NSMetadataQueryUbiquitousDataScope
Search all files not in the Documents directories of the application’s iCloud container directories.

NSMetadataQueryIndexedLocalComputerScope
Search all indexed local mounted volumes including the current user’s home directory (even if the home directory is remote).

NSMetadataQueryIndexedNetworkScope
Search all indexed user-mounted remote volumes.

**Comment by 15four** [comment]
It seems like either of these would include it, but that's just a guess.

NSMetadataQueryLocalComputerScope
Search all local mounted volumes, including the user home directory. The user’s home directory is searched even if it is a remote volume.

NSMetadataQueryNetworkScope
Search all user-mounted remote volumes.

It is an afp:// mounted AppleShare drive.

**Comment by 15four** [comment]
I know that the drive is not indexed by Spotlight, though.

**Comment by petetak** [comment]
Hi,
ok right - this won't work then - drives have to be indexed with spotlight to work with Recents - it's the core tech behind it...
