### ISSUE TITLE
find .sublime-* project files

### ISSUE THREAD

**Issue by lunelson** [teammixture/recents-settings#20]
It would be nice if Recents found the `.sublime-*` files related to a project. I guess this is a bit more complex, since a grunt project—for example—is defined by it's own settings file; but the option of "editor" could have it's own sub-set of parameters which could reference a search for those files. They're not always in the same directory though, so it would also have to search up higher directories too e.g. for wordpress the `.sublime-*` files might be at the root level though the grunt stuff is in the theme folder.

**Comment by teammixture** [comment]
You have the ability to write the logic you want into the settings file for your own use case.

Sublime is a specific use case and not everyones, our aim is add defaults that match specific project types.

**Comment by pekala** [comment]
And how would you go about doing that? I guess it should be possible with the "arguments" attribute on buttons, but I can't figure out how to do it.

**Comment by teammixture** [comment]
It's documented in the readme how you add custom project types and whats possible https://github.com/teammixture/recents-settings

**Comment by pekala** [comment]
Yes, it is just that the "arguments" attribute is present in all the examples, but is never actually used. What kind of arguments can I supply? I guess not command line arguments, because this: `--project project.sublime-project` doesn't work
