### ISSUE TITLE
Level of Support

### ISSUE THREAD

**Issue by ChrisSumner** [teammixture/recents-settings#32]
Hi there,

This isn't a bug as such however these doesn't seem to be much in terms of documentation of this app. I was searching for the App in the App Store however it doesn't seem to be listed anymore and the website is no longer functioning. 

My question is, is Recents being supported anymore or is it slowly dying off?

**Comment by keihikaru0001** [comment]
Ward turn to power of money.

**Comment by teammixture** [comment]
Hi
Sorry - it's kind of been sidelined as we've been busy with other things. I haven't used it for a while - does it still work? 
Maybe we will clean it up and open source it if it's useful to anyone
