### ISSUE TITLE
Crash issue

### ISSUE THREAD

**Issue by wesleyburden** [teammixture/recents-settings#4]
Hi guys

Loving the look of this! 

I opened the settings, changed my editor to Coda 2 for Mixture and WordPress projects and then run my latest Mixture project.  Everything opened fine then I quit Mixture and Coda and Recents has crashed.  The icon is still in the tool bar but when I out the mouse over it I get the spinning wheel of death and no response when clicking.

I shall force quit and try again.

Wes

**Comment by wesleyburden** [comment]
OK so it seems every time I try and run a project it crashes.  This is what the activity monitor looks like once it's crashed.  Mixture opens fine but Coda doesn't.

![screen shot 2013-12-11 at 09 49 07](https://f.cloud.github.com/assets/2233554/1722717/b1dba2da-6249-11e3-9e53-a5e23c6a6ae2.png)

**Comment by teammixture** [comment]
Hi Wes do you get any console logs, could you try again and see if anything is logged

**Comment by teammixture** [comment]
Wondering if Coda is doing something on disk when it closes

**Comment by wesleyburden** [comment]
It seems to crash right off the bat whether coda is open or not.  Here is a console log.  I'd opened Recents and clicked run on my latest Mixture project.  Now recents is crashed.
![screen shot 2013-12-11 at 10 05 24](https://f.cloud.github.com/assets/2233554/1722842/1b96665e-624c-11e3-8afd-2aa031562dec.png)

**Comment by teammixture** [comment]
We've located the possible issue, this will hopefully be resolved in 0.06 coming shortly
